### ISSUE TITLE
SystemMethods.CurrentDateTime not producing correct syntax with SQLite db

### ISSUE THREAD

**Issue by jannesuo** [schambers/fluentmigrator#743]
Hi,

Having the following migration in c# class:
`Create.Table("SomeTableName"").WithColumn("Modified").AsDateTime().WithDefaultValue(SystemMethods.CurrentDateTime);`

produces SQL as the following:
`CREATE TABLE "SomeTableName" ("Modified" DATETIME NOT NULL DEFAULT datetime('now','localtime'))`

... that is not working. To generate proper syntax, there should be extra parenthesis around "datetime()" -method, i.e.

`CREATE TABLE "SomeTableName" ("Modified" DATETIME NOT NULL DEFAULT (datetime('now','localtime')))`

I tested the generated SQL in my sqlite db use case and after adding these extra parenthesis, it started working. The issue is discussed here: [Stackoverflow: Can I create a datetime column with default value in sqlite3?](http://stackoverflow.com/a/2615390)

File to fix:
fluentmigrator/src/FluentMigrator.Runner/Generators/SQLite/SQLiteColumn.cs

**Comment by ParagonIG** [comment]
Hi,
I've just run into this problem, pending a fix does anyone know of a work around?
Ian.

**Comment by ParagonIG** [comment]
OK, I had a quick look at the code and it appears that there are two ways to fix this:
a) Modify FormatSystemMethods() in SQLiteColumn to output (datetime('now','localtime')) rather than datetime('now','localtime') for SystemMethods.CurrentDateTime.
b) Override FormatDefaultValue() for SQLiteColumn so that all defaults are encapsulated in parenthesizes, thus allowing any expression to work.

a is the simplest but as it seems that the parenthesis requirement is from the DEFAULT command rather than the datetime() command b looks like a more conceptually pure approach.

A fix for this (either solution) would be really helpful.

**Comment by bjarki** [comment]
Where can I find a release with this fix? The latest version on nuget is from 5/31/2016

**Comment by bjarki** [comment]
Found the latest version under https://teamcity.jetbrains.com/viewType.html?buildTypeId=bt82&guest=1
